### ISSUE TITLE
Do you plan to define an "install" target ?

### ISSUE THREAD

**Issue by vincent-picaud** [vimmy-io/cxp#1]
First, thanks for sharing. Having a good project skeleton (template) is always a gain of time.

I have just tested your build template, however, AFAIK the "install" target is not defined.

This feature is very handy when there are several modules that depend on each others and it is really nice to have a working cmake find_package() function at disposal.

My question is: are you considering developing this feature?

Best,
VP

**Comment by vimmy-io** [comment]
As far as install targets go specifically, that definitely needs doing at some point.

I'm basically following a lot of advice from [Daniel Pfeifer's talk](https://www.youtube.com/watch?v=bsXLMQ6WgIk) and there is a lot of stuff yet to be done including but not limited to:
- install targers
- find_package / write_basic_package_
- test integration
- cpack
- Configuring C++ conditional compilation
- ...

However, I also want to try and keep a minimum skeleton making it slightly tricky to have few of the aforementioned features as opt-in or easily configurable. While it's going to take me a while to implement it (I'm juggling a few other things on my end as well), I unfortunately cannot guarantee when it would be completed but hopefully a month or so.

**Comment by vincent-picaud** [comment]
Thanks for your detailed answer and interesting readings. I completely understand that any added feature requires a lot of work. I do not know if someone else shares this opinion but I think install target is a valuable feature which must have a high priority (IMHO). In the past I have also coded a project skeleton generator, https://github.com/vincent-picaud/CMakeScript,  emphasizing on modularization but the doc is not good and it uses "old" cmake.
Again thanks for sharing, long life and success for this project!

**Comment by vimmy-io** [comment]
That's a good point, I'll see if I can implement this sooner!

**Comment by vimmy-io** [comment]
I've now added this to just the [engine lib](https://github.com/crezefire/cxp/blob/cdd213cc5d10a3391733dde7ba6a06ecc55dd619/libs/engine/CMakeLists.txt#L30-L86) and it's related [config file](https://github.com/crezefire/cxp/blob/master/libs/engine/EngineConfig.cmake). It should hopefully get you going and using it for other libraries / executables as well.

And as always, the point with this whole project is to give a base so you can feel free to modify and change it as it suits your needs.

**Comment by vincent-picaud** [comment]
Thanks! I am going to test it.

**Comment by vimmy-io** [comment]
np, feel free to reopen this issue if it's not working or something is missing
